### ISSUE TITLE
Setting Up has_many :through Associations

### ISSUE THREAD

**Issue by francesharlow** [francesharlow/recipe_wiki#1]
Hi Anna,

I'm sorry to interrupt your weekend! I hope it's been great thus far.

If you have a moment, I'd really appreciate some help setting up the associations between my categories and articles. I've tried a number of different techniques but nothing's worked yet (I'm sorry in advance -- this is going to get long as I try to explain as clearly as possible).

I'd like to be able to use @category.articles and @article.categories methods in my server, so I can list the categories that apply to an individual article view and, elsewhere on the web application, the articles that belong to an each category. As such, I've set up the following migrations:

```
class Article < ActiveRecord::Base
  belongs_to :author, class_name: "User"
  has_many :edits, class_name: "Edit", foreign_key: "article_id"
  has_many :article_categories
  has_many :categories, through: :article_categories
```

and 

```
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
end
```

so that 

```
class ArticleCategory < ActiveRecord::Base
  belongs_to :articles
  belongs_to :categories
end
```

My schema runs properly, as written:

```
CREATE TABLE articles (
  id INTEGER PRIMARY KEY,
  title VARCHAR,
  ingredients TEXT,
  directions TEXT,
  img_url TEXT,
  created_on DATETIME,
  author_id INTEGER
);

CREATE TABLE categories (
  id INTEGER PRIMARY KEY,
  name VARCHAR
);

CREATE TABLE article_categories (
  article_id INTEGER,
  category_id INTEGER
);
```

However, when I try to run my db/seeds.rb file

```
c1 = Category.create(name: "breakfast")
c2 = Category.create(name: "vegan")

c1.article_categories.push(a1)
c2.article_categories.push(a2)
```

I get an "Could not find table 'article_categories' (ActiveRecord::StatementInvalid)" error. I've tried futzing around and switching the variable order (a1 and a2 into c1 and c2, for instance), as well as c1.articles.push(a1) just to see what would happen, but that gave me a "uninitialized constant Category::Articles (NameError)" error, unsurprisingly.

I think I'm pretty close to getting it to work, but I need a little hint. I'd really love to get to MVP functionality before tomorrow morning. In the meantime, I'll get to work on styling :)

Thanks so much!

**Comment by annarankin** [comment]
Hey Frances, happy Sunday! Right now, you're trying to push an article into the `article_categories` table, which will cause problems. Try just creating new `ArticleCategories` instead!

**Comment by annarankin** [comment]
Also, your table should be `articles_categories`, and your model should be properly pluralized as well :v:

**Comment by francesharlow** [comment]
Thanks, Anna! I actually just thought to try that as soon as I posted this. And I think it worked (no errors so far, racking up momentarily). 

And double thanks for the tip on the naming conventions -- this article (http://blog.flatironschool.com/why-you-dont-need-has-and-belongs-to-many/) didn't pluralize so I thought that was best practice. Will fix right now!
