### ISSUE TITLE
Help with Heroku and Creating New articles_categories

### ISSUE THREAD

**Issue by francesharlow** [francesharlow/recipe_wiki#2]
Hi Anna,

First, I just tried pushing my changes to Heroku and I'm now getting an internal server error when I try to log in. :/

Second, in my server.rb file, I'd like to add a new instance of articles_categories when the user adds an category to a article, but unfortunately it just breaks my code (hence the commenting out). I can successfully add a category, but it isn't adding to the joint-table, which means it won't be linked to the given article.

```
    post "/articles/:id/categories" do
      redirect to "/" if !session[:user_id]
      @article = Article.find(params[:id])
      @category = Category.create(
        name: params[:name]
        )
      # @articles_categories = ArticlesCategory.create (
      #   article_id: params[:id],
      #   category_id: @category.id,
      #   )
      redirect to "/articles/#{@article.id}"
    end
```

Thanks!

**Comment by phlco** [comment]
It's a "join" not "joint"!

:maple_leaf: :fire: :v:

**Comment by annarankin** [comment]
Hey Frances! So, is anything being added to the join table, or is it throwing you an error?

**Comment by francesharlow** [comment]
Great question! It's no longer throwing me an error, but it doesn't seem to be pushing the new tags into the articles-category join(t) table, either. They just exist, without any associations. I'm also signed up to see Abner soon so hopefully he can help me figure it out.

**Comment by annarankin** [comment]
Gotcha - can you push up the latest version of your code?

**Comment by francesharlow** [comment]
Done and done!

**Comment by francesharlow** [comment]
Aha, the error is back.

**Comment by annarankin** [comment]
Hey Frances, found a minor syntax error - you had an extra space and an extraneous comma:

``` ruby
      @articles_category = ArticlesCategory.create({
        article_id: params[:id],
        category_id: @category.id
        })
```

**Comment by francesharlow** [comment]
You're a genius! Thank you.

**Comment by annarankin** [comment]
:v: :100:  :v:
